### ISSUE TITLE
Querying GM2MFields by primary key when foreign elements' pk is an UUIDField raises an OverflowError

### ISSUE THREAD

**Issue by Zeerooth** [tkhyn/django-gm2m#52]
To replicate:

1. Create a project with the following models (SQLite as database engine):
```python
from django.db import models
from gm2m import GM2MField
import uuid

class ClassA(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    elements = GM2MField()

class ClassB(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

2. Then try to run the following code:
```python
obj1 = ClassA.objects.create()
obj2 = ClassB.objects.create()
obj1.elements = [obj2]
obj1.elements.get(pk=obj2.id)
```

It will result in an error:
```python
Traceback (most recent call last):
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
OverflowError: Python int too large to convert to SQLite INTEGER

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/your/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/path/to/your/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/path/to/your/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/path/to/project/gm2m-test/src/testproj/views.py", line 7, in test_view
    obj1.elements.get(pk=obj2.id)
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/path/to/your/lib/python3.7/site-packages/gm2m/query.py", line 35, in __iter__
    *extra_select):
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/query.py", line 144, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1092, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/path/to/your/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/sqlite3/operations.py", line 150, in last_executed_query
    params = self._quote_params_for_last_executed_query(params)
  File "/path/to/your/lib/python3.7/site-packages/django/db/backends/sqlite3/operations.py", line 139, in _quote_params_for_last_executed_query
    return cursor.execute(sql, params).fetchone()
OverflowError: Python int too large to convert to SQLite INTEGER
```

**Comment by kdtldr** [comment]
Did you find this solution? Facing similar issue as well.

**Comment by Zeerooth** [comment]
@kdtldr Nope, sorry, I wish I could help, but I've never got to the core of this issue and because of this I dropped `django-gm2m` in my project altogether and went with different model structure.
