### ISSUE TITLE
object has no attribute '_prefetched_objects_cache'

### ISSUE THREAD

**Issue by wrabit** [tkhyn/django-gm2m#69]
This is from an install of the the unmerged PR, trying with Django 5.1:

- #68 

But I am hoping you can recognise if this is something obvious since I am new to the package.. (TIA!)

### Non-generic side model:

```python
class Owner(models.Model):
    assets = GM2MField('Table', through='OwnerAsset', related_name='owners')
```

### Link through model

```python
class OwnerAsset(models.Model):
    # these are from legacy but I can't see how it's negatively affecting
    owner = models.ForeignKey('Owner', on_delete=models.CASCADE, related_name='owner_assets')
    owner_type = models.ForeignKey('OwnerType', on_delete=models.SET_NULL, null=True, blank=True)

    asset = GenericForeignKey('asset_type', 'asset_id')
    asset_type = models.ForeignKey(ContentType, on_delete=models.PROTECT)
    asset_id = models.PositiveIntegerField()
```

### Generic side model:

```python
class Table(models.Model):
    objects = DeferredDataManager()
```

### Just for reference

```python
class DeferredDataManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().defer('data')
```

### Traceback:

```bash
>>> table.owners.all()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gm2m/managers.py", line 24, in get_queryset
    ._prefetched_objects_cache[self.prefetch_cache_name]
AttributeError: 'Table' object has no attribute '_prefetched_objects_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 164, in all
    return self.get_queryset()
  File "/usr/local/lib/python3.10/site-packages/gm2m/managers.py", line 28, in get_queryset
    return self._get_queryset(using=db)._next_is_sticky() \
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'ownerasset' into field. Choices are: asset_owners, assets, created_at, email, first_name, id, last_name, owner_assets, tableowner, title, updated_at
```

**Comment by wrabit** [comment]
(cleared up some leftover code from the generic-side model)

**Comment by matejhazala** [comment]
Thank you, will have a look

**Comment by matejhazala** [comment]
i cant reproduce it, added test for it in my tests branch https://github.com/matejhazala/django-gm2m/tree/tests,
see folder "issue69", can you modify it to reproduce the issue?
